[general]
import = [
"~/.config/alacritty/tokyo-night.toml",
]

[env]
term = "xterm-256color"

[window]

opacity = 0.7
blur = true

[font]
normal = { family = "FiraMonoNerd Font", style = "Regular" }
bold = { family = "FiraMonoNerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }



