[general]
import = [
"~/.config/alacritty/tokyo-night-storm.toml",
]

[env]
term = "xterm-256color"


[font]
normal = { family = "FiraMonoNerd Font", style = "Regular" }
bold = { family = "FiraMonoNerd Font", style = "Bold" }
italic = { family = "FiraMono Nerd Font", style = "Italic" }
bold_italic = { family = "FiraMono Nerd Font", style = "Bold Italic" }



