# TOOL-inspired Alacritty theme (dark grey dominant, based on wallpaper)

[colors.primary]
	background = '#181715'   
	foreground = '#dbd4db'

[colors.normal]
	black      = '#181715'
	red        = '#b21204'
	yellow     = '#7b8749'
	green      = '#4f6a41'
	blue       = '#241b6c'
	magenta    = '#a20e48'
	cyan       = '#6b58b1'
	white      = '#dbd4db'

[colors.bright]
    	black      = '#2e2b27'
    	red        = '#ff2a1a'
    	yellow     = '#c6d95a'
	green      = '#7fc85a'
	blue       = '#3a2cff'
	magenta    = '#ff2b7f'
	cyan       = '#9d8cff'
	white      = '#ffffff'

[colors.cursor]
    	text       = '#181715'
    	cursor     = '#dbd4db'
  
[colors.selection]
    	text       = '#2e2b27'
    	background = '#a20e48'

