# TOOL-inspired Alacritty theme (dark grey dominant, based on wallpaper)

[colors.primary]
    background= '0x0c0c0d'   # deep neutral grey-black from the background
    foreground= '0xc8c8c8'   # light grey from the collar/light areas

[colors.normal]
    black=   '0x1a1a1b'
    red=     '0xc0211a'
    green=   '0x5a4c45'
    yellow=  '0xcc6a1d'
    blue=    '0x3b2f45'
    magenta= '0x7a3d5c'
    cyan=    '0x5f6c6a'
    white=   '0xb0b0b0'

[colors.bright]
    black=   '0x3a3a3d'
    red=     '0xff4535'
    green=   '0x7a6e61'
    yellow=  '0xf08a36'
    blue=    '0x635578'
    magenta= '0xa65b7e'
    cyan=    '0x8aa09a'
    white=   '0xe0e0e0'
  
[colors.cursor]
    text=   '0x0c0c0d'
    cursor= '0xc8c8c8'
  
[colors.selection]
    text=       '0xc8c8c8'
    background= '0x1a1a1b'

