#!/bin/bash

# Load conda
CONDA_BASE=$(conda info --base)
source "$CONDA_BASE/etc/profile.d/conda.sh"

# Packages passed as arguments
PACKAGES="$@"

# Loop through all environments
for env in $(conda env list | awk 'NR>1 && 1="#" {print $1}'); do
	conda activate $env
	pip install $PACKAGES
done
echo "Pip install completed in all environments"

