#!/usr/bin/python3
import gi, subprocess
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk, GLib, Gdk

def run(cmd):
    return subprocess.run(cmd, shell=True, text=True, capture_output=True).stdout.strip()

def set_brightness(v):
    subprocess.run(f"xrandr --output DP-0 --brightness {float(v)/100}", shell=True)

def get_brightness():
    out = run("xrandr --verbose | grep -i brightness | head -n1")
    try:
        return int(float(out.split()[1]) * 100)
    except Exception:
        return 50

def get_default_sink():
    return run("pactl get-default-sink")

def get_volume(sink):
    out = run(f"pactl get-sink-volume {sink} 2>/dev/null | head -n1")
    parts = out.split()
    try:
        return int(parts[4].strip('%'))
    except Exception:
        return 50

def set_volume(sink, v):
    subprocess.run(["pactl", "set-sink-volume", sink, f"{int(v)}%"])

def get_default_source():
    return run("pactl get-default-source")

def get_mic(source):
    out = run(f"pactl get-source-volume {source} 2>/dev/null | head -n1")
    parts = out.split()
    try:
        return int(parts[4].strip('%'))
    except Exception:
        return 50

def set_mic(source, v):
    subprocess.run(["pactl", "set-source-volume", source, f"{int(v)}%"])

def get_battery_info():
    return run("upower -i /org/freedesktop/UPower/devices/battery_BAT0 | egrep 'percentage:|state:|time to empty:'")

class PopupWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Controls")
        self.set_border_width(8)
        self.set_default_size(320, 220)
        self.set_decorated(False)
        self.set_resizable(False)
        self.set_keep_above(True)
        self.set_type_hint(Gdk.WindowTypeHint.POPUP_MENU)
        self.set_skip_taskbar_hint(True)
        self.set_focus_on_map(True)

        self._update_id = None

        self.connect("key-press-event", self.on_key_press)
        self.connect("realize", self._on_realize)
        self.connect("show", self._on_show)
        self.connect("hide", self._on_hide)

        box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=8)
        self.add(box)

        # Brightness
        box.pack_start(Gtk.Label(label="Brightness"), False, False, 0)
        b = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 100, 1)
        b.set_value(get_brightness())
        b.connect("value-changed", lambda s: set_brightness(s.get_value()))
        box.pack_start(b, False, False, 0)

        # Output volume
        sink = get_default_sink()
        box.pack_start(Gtk.Label(label=f"Output Volume ({sink})"), False, False, 0)
        vol = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 150, 1)
        vol.set_value(get_volume(sink))
        vol.connect("value-changed", lambda s: set_volume(sink, s.get_value()))
        box.pack_start(vol, False, False, 0)

        # Microphone
        src = get_default_source()
        box.pack_start(Gtk.Label(label=f"Microphone ({src})"), False, False, 0)
        mic = Gtk.Scale.new_with_range(Gtk.Orientation.HORIZONTAL, 0, 150, 1)
        mic.set_value(get_mic(src))
        mic.connect("value-changed", lambda s: set_mic(src, s.get_value()))
        box.pack_start(mic, False, False, 0)

        # Battery
        box.pack_start(Gtk.Label(label="Battery Info"), False, False, 0)
        self.bat_label = Gtk.Label(label=get_battery_info())
        self.bat_label.set_xalign(0)
        box.pack_start(self.bat_label, False, False, 0)

        # Close button
        close_btn = Gtk.Button(label="Close")
        close_btn.connect("clicked", lambda w: self.hide())
        box.pack_start(close_btn, False, False, 0)

    def _on_realize(self, *args):
        gdkwin = self.get_window()
        if gdkwin:
            try:
                gdkwin.set_override_redirect(True)
            except Exception:
                pass

    def on_key_press(self, widget, event):
        self.hide()

    def _on_show(self, *args):
        self._update_id = GLib.timeout_add_seconds(5, self._refresh_battery)
        self._grab_pointer_keyboard()

    def _on_hide(self, *args):
        if self._update_id:
            GLib.source_remove(self._update_id)
            self._update_id = None
        gdkwin = self.get_window()
        if gdkwin:
            gdkwin.ungrab_pointer(Gdk.CURRENT_TIME)
            gdkwin.ungrab_keyboard(Gdk.CURRENT_TIME)

    def _refresh_battery(self):
        self.bat_label.set_text(get_battery_info())
        return True

    def popup_at_pointer(self):
        self.show_all()
        self.grab_focus()
        GLib.idle_add(self._position_near_pointer)

    def _position_near_pointer(self):
        display = Gdk.Display.get_default()
        pointer = display.get_pointer()[1:3]

        monitor = display.get_monitor_at_point(*pointer)
        geo = monitor.get_geometry()
        win_width, win_height = self.get_size()

        px = max(geo.x, min(pointer[0], geo.x + geo.width - win_width))
        py = max(geo.y, min(pointer[1] + 16, geo.y + geo.height - win_height))

        self.move(px, py)
        return False

    def _grab_pointer_keyboard(self):
        gdkwin = self.get_window()
        if gdkwin:
            gdkwin.grab_pointer(True,
                                Gdk.EventMask.BUTTON_PRESS_MASK,
                                None, None, Gdk.CURRENT_TIME)
            gdkwin.grab_keyboard(True, Gdk.CURRENT_TIME)

    def do_button_press_event(self, event):
        self.hide()
        return True

    def do_key_press_event(self, event):
        self.hide()
        return True

def main():
    popup = PopupWindow()

    tray_icon = Gtk.StatusIcon()
    tray_icon.set_from_icon_name("utilities-system-monitor")
    tray_icon.set_tooltip_text("Controls")
    tray_icon.connect("activate", lambda icon: popup.popup_at_pointer())

    Gtk.main()

if __name__ == "__main__":
    main()


