#!/bin/bash

# update dwm config
rm -rf $HOME/.config/dwmdesktop/dwm
cp -r  $HOME/.config/dwm  $HOME/.config/dwmdesktop

# update autostart
rm -rf $HOME/.config/dwmdesktop/autostart.sh
cp $HOME/.dwm/autostart.sh  $HOME/.config/dwmdesktop

# update scripts
rm -rf $HOME/.config/dwmdesktop/Scripts
cp -r $HOME/Scripts $HOME/.config/dwmdesktop
